import { chmod, mkdir, writeFile } from "node:fs/promises";
import { join } from "node:path";
import { DEFAULT_PROVIDER_KEYS, WORKER_ENV_PASSTHROUGH } from "./env.js";

const ENV_NAME = /^[A-Z_][A-Z0-9_]*$/;

/**
 * Bash launcher shim used by visible (pane) workers: rebuilds the env with `env -i` exactly like
 * buildWorkerEnv and execs the real pi through the sandbox profile wrapArgv left in the run dir.
 * Lines are plain strings (no template literal) so bash `${...}` never collides with JS.
 */
export function renderLauncherScript(providerKeys: readonly string[] = DEFAULT_PROVIDER_KEYS): string {
  for (const key of providerKeys) {
    if (!ENV_NAME.test(key)) throw new Error(`renderLauncherScript: "${key}" is not a valid environment variable name`);
  }
  const passthrough = [...WORKER_ENV_PASSTHROUGH, ...providerKeys].join(" ");
  const lines = [
    '#!/usr/bin/env bash',
    '# pi-sdlc-factory launcher shim: execs the real pi under the worker env scrub and sandbox.',
    '# Generated by installLauncher(); edits are overwritten on the next /factory setup.',
    'set -euo pipefail',
    '',
    'self_dir="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"',
    '',
    'if [ "${PI_SDLC_AGENT_MODE:-}" != "1" ] || [ -z "${PI_SDLC_RUN_ID:-}" ] || [ -z "${PI_SDLC_RUNS_DIR:-}" ]; then',
    '  echo "pi-sdlc-factory launcher: refusing to start outside a factory run (PI_SDLC_AGENT_MODE, PI_SDLC_RUN_ID and PI_SDLC_RUNS_DIR must be set)" >&2',
    '  exit 64',
    'fi',
    '',
    'real_pi="${PI_SDLC_REAL_PI:-}"',
    'if [ -z "$real_pi" ]; then',
    '  old_ifs="$IFS"; IFS=:',
    '  for d in ${PATH:-}; do',
    '    [ -n "$d" ] || continue',
    '    [ "$d" = "$self_dir" ] && continue',
    '    if [ -x "$d/pi" ]; then real_pi="$d/pi"; break; fi',
    '  done',
    '  IFS="$old_ifs"',
    'fi',
    'if [ -z "$real_pi" ]; then',
    '  echo "pi-sdlc-factory launcher: real pi not found on PATH" >&2',
    '  exit 65',
    'fi',
    '',
    'run_dir="${PI_SDLC_RUNS_DIR}/${PI_SDLC_RUN_ID}"',
    'scrub_dir="$(mktemp -d "${TMPDIR:-/tmp}/pi-sdlc-scrub.XXXXXX")"',
    'mkdir -p "$scrub_dir/gh"',
    ': > "$scrub_dir/gitconfig"',
    '',
    'scrubbed=()',
    `for v in ${passthrough}; do`,
    '  if [ -n "${!v+x}" ]; then scrubbed+=("$v=${!v}"); fi',
    'done',
    'for v in $(compgen -A variable PI_SDLC_); do',
    '  scrubbed+=("$v=${!v}")',
    'done',
    'scrubbed+=(',
    '  "GIT_CONFIG_GLOBAL=$scrub_dir/gitconfig"',
    '  "GIT_CONFIG_NOSYSTEM=1"',
    '  "GIT_TERMINAL_PROMPT=0"',
    '  "GIT_ASKPASS=/usr/bin/false"',
    '  "GIT_SSH_COMMAND=ssh -o BatchMode=yes -o IdentitiesOnly=yes -i /nonexistent"',
    '  "GH_CONFIG_DIR=$scrub_dir/gh"',
    '  "NPM_CONFIG_USERCONFIG=/dev/null"',
    ')',
    '',
    'if [ -f "$run_dir/sandbox.off" ]; then',
    '  exec env -i "${scrubbed[@]}" "$real_pi" "$@"',
    'fi',
    'if [ -f "$run_dir/sandbox.sb" ] && command -v sandbox-exec >/dev/null 2>&1; then',
    '  exec env -i "${scrubbed[@]}" sandbox-exec -f "$run_dir/sandbox.sb" "$real_pi" "$@"',
    'fi',
    'if [ -f "$run_dir/sandbox.bwrap" ] && command -v bwrap >/dev/null 2>&1; then',
    '  bwrap_args=()',
    '  first=1',
    '  while IFS= read -r line || [ -n "$line" ]; do',
    '    if [ "$first" = 1 ]; then first=0; continue; fi',
    '    [ -n "$line" ] && bwrap_args+=("$line")',
    '  done < "$run_dir/sandbox.bwrap"',
    '  exec env -i "${scrubbed[@]}" "${bwrap_args[@]}" "$real_pi" "$@"',
    'fi',
    'echo "pi-sdlc-factory launcher: no sandbox profile in $run_dir (expected sandbox.sb, sandbox.bwrap, or sandbox.off to opt out)" >&2',
    'exit 66',
  ];
  return `${lines.join("\n")}\n`;
}

export const LAUNCHER_SCRIPT = renderLauncherScript(DEFAULT_PROVIDER_KEYS);

export interface InstallLauncherOptions {
  providerKeys?: readonly string[];
}

export async function installLauncher(home: string, opts: InstallLauncherOptions = {}): Promise<string> {
  const binDir = join(home, "bin");
  await mkdir(binDir, { recursive: true, mode: 0o700 });
  const path = join(binDir, "pi");
  await writeFile(path, renderLauncherScript(opts.providerKeys), { mode: 0o755 });
  await chmod(path, 0o755); // writeFile's mode only applies to newly created files
  return path;
}
