export type { KeyringPort, SecretMeta, SecretName, VaultRecord, VaultStore } from "./types.js";
export { MemoryVaultStore } from "./memory-store.js";
export { FakeKeyring } from "./fake-keyring.js";
export { SqliteVaultStore } from "./sqlite-store.js";
export { KEYRING_ACCOUNT, KEYRING_SERVICE, osKeyring } from "./keyring.js";
export { assertSecretName, probeVault, Vault, VaultUnavailableError, vaultPath } from "./vault.js";
export { installInputGuard, looksLikeSecret } from "./input-guard.js";
export { SECRET_REF, resolveSecretRef } from "./resolve.js";
export { injectHostEnv } from "./host-env.js";
export { PROVIDER_TOKEN_PATTERNS, makeScrubber } from "./scrubber.js";
export { TOKEN_SHAPES, scrubFile, scrubSeed, knownVaultValues } from "./scrub.js";
export { asSecretName, bindSecret, secretsBound, vaultNameOf } from "./bind.js";
export { exportVault, importVault } from "./export.js";
export type { ExportEnvelope } from "./export.js";
export { runWithSecret, wouldDumpEnv } from "./inject.js";
